import { editorURL } from './editor-url';
import { chromium, expect } from '@playwright/test';
import { strict as assert } from 'node:assert';
import fixture from '../../../tools/preview-fixture';
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1100}});
const page = await context.newPage();
const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(editorURL());
  await page.waitForFunction(() => window.sugarMaple.ready);
  await page.evaluate(async nodes => {
    const d = await window.sugarMaple.dispatch('document.get');
    await window.sugarMaple.dispatch('transaction.apply', {documentId:d.documentId,expectedRevision:d.revision,requestId:crypto.randomUUID(),operations:nodes.map(n=>({type:'node.add',node:{...n,pageId:d.document.pages[0].id}}))});
    await window.sugarMaple.dispatch('selection.set',{id:'login'});
  }, fixture.document.nodes);
  const before = await page.evaluate(() => window.sugarMaple.dispatch('document.checkpoint'));
  await page.context().setOffline(true);
  await page.getByRole('button',{name:'▶ Preview'}).click();
  const preview = page.getByRole('dialog',{name:'Prototype preview',exact:true});
  const email = preview.getByRole('textbox',{name:'Email',exact:true});
  await email.fill('Only in preview');
  await page.getByLabel('Preview viewport').selectOption('393');
  await expect(preview.locator('.preview-stage')).toHaveCSS('width','393px');
  await page.getByLabel('Preview viewport').selectOption('custom');
  await page.getByLabel('Custom preview width').fill('512'); await page.getByLabel('Custom preview width').press('Tab');
  await page.getByLabel('Custom preview height').fill('640'); await page.getByLabel('Custom preview height').press('Tab');
  await expect(preview.locator('.preview-stage')).toHaveCSS('width','512px');
  await expect(preview.locator('.preview-stage')).toHaveCSS('height','640px');
  await page.getByLabel('Custom preview height').fill('1800'); await page.getByLabel('Custom preview height').press('Tab');
  await preview.locator('.preview-scroll').hover(); await page.mouse.wheel(0,300);
  await expect.poll(() => preview.locator('.preview-scroll').evaluate(el => el.scrollTop)).toBeGreaterThan(0);
  await page.getByLabel('Custom preview height').fill('640'); await page.getByLabel('Custom preview height').press('Tab');
  await page.getByLabel('Custom preview width').fill('10000'); await page.getByLabel('Custom preview width').press('Tab');
  await expect(preview.getByRole('alert')).toContainText('240 to 4096');
  await expect(preview.locator('.preview-stage')).toHaveCSS('width','512px');
  await page.getByLabel('Custom preview width').fill('512'); await page.getByLabel('Custom preview width').press('Tab');
  await page.getByRole('button',{name:'Developer Inspect',exact:true}).click();
  await preview.locator('[data-node-id="go"]').click();
  const details = preview.getByRole('complementary',{name:'Developer Inspect details'});
  await expect(details).toContainText('Continue action');
  await expect(details).toContainText('Component: Account card');
  await expect(preview.locator('[data-node-id="welcome"]')).toHaveCount(0);
  await expect(email).toHaveValue('Only in preview');
  await expect(email).toHaveAttribute('readonly','');
  await page.getByRole('button',{name:'Close preview'}).focus();
  await page.keyboard.press('Tab');
  await expect(page.getByLabel('Preview viewport')).toBeFocused();
  assert.deepEqual(await page.evaluate(() => window.sugarMaple.dispatch('document.checkpoint')), before);
  await page.getByRole('button',{name:'Developer Inspect',exact:true}).click();
  await preview.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(preview.locator('[data-node-id="welcome"]')).toBeVisible();
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await expect(email).toHaveValue('Only in preview');
  await page.getByRole('button',{name:'Reset preview'}).click();
  await expect(email).toHaveValue('mock@example.test');
  assert.deepEqual(await page.evaluate(() => window.sugarMaple.dispatch('document.checkpoint')), before);
  await page.getByRole('button',{name:'Close preview'}).click();
  await expect(page.getByRole('button',{name:'▶ Preview'})).toBeFocused();
  await page.context().setOffline(false);
  const isolated = await page.context().newPage();
  await isolated.goto(editorURL('#preview'));
  await isolated.waitForFunction(() => window.sugarMaplePreview?.ready);
  assert.equal(await isolated.evaluate(() => typeof window.sugarMaple),'undefined');
  await isolated.evaluate(value => window.sugarMaplePreview!.receive(value), fixture);
  await expect(isolated.getByRole('textbox',{name:'Email',exact:true})).toHaveValue('mock@example.test');
  await isolated.getByRole('textbox',{name:'Email',exact:true}).fill('Isolated input');
  const next = structuredClone(fixture); next.revision = 1; next.document.nodes.find(n=>n.id==='go')!.text = 'Continue live';
  await isolated.evaluate(value => window.sugarMaplePreview!.receive(value),next);
  await expect(isolated.getByRole('button',{name:'Continue live',exact:true})).toBeVisible();
  await expect(isolated.getByRole('textbox',{name:'Email',exact:true})).toHaveValue('Isolated input');
  await isolated.evaluate(value => window.sugarMaplePreview!.receive(value),fixture);
  await expect(isolated.getByRole('button',{name:'Continue live',exact:true})).toBeVisible();
  await isolated.evaluate(() => window.sugarMaplePreview!.dispose());
  await expect(isolated.locator('prototype-preview')).toHaveCount(0);
  assert.equal(await isolated.evaluate(() => typeof window.sugarMaplePreview),'undefined');
  assert.deepEqual(errors,[]);
  console.log('PASS: offline custom viewport validation, nested component Inspect without action/input mutation, ephemeral reset, authoring focus/checkpoint preservation, isolated bootstrap/feed/live values/stale snapshot rejection and disposal');
} finally { await browser.close(); }
