import { resolve } from 'node:path';
const folder=resolve('build/library-preview-comparison');
const comparison=await Bun.file(resolve(folder,'comparison.json')).json(),cost=await Bun.file(resolve(folder,'package-cost.json')).json();
const results=comparison.results;
const kb=(bytes:number)=>(bytes/1024).toFixed(1)+' KiB';
const rows=[
  ['Canvas authoring','Same scene; inspector props and undo','Painted controls; Layers/inspector edit them','Library identity changes; package-only styles are not projected','Canvas image plus keyboard transform handles','Existing editor bundle'],
  ['Semantic DOM preview','Same resolved geometry; ephemeral input retained','Real HTML textbox/button','Semantic appearance; no package variant styling','Named HTML controls; isolated authoring-free feed',kb(cost.semanticFixture.raw)+' fixture HTML'],
  ['Real web package','Typed props; real controls and action/change events','Real shadow-DOM controls','Actual brand variant; intrinsic sizing differs from authored scene','Named textbox/button; visible label and paragraph header',kb(cost.addedLibraryRuntime.raw)+' JS/CSS; '+kb(cost.addedLibraryRuntime.brotli)+' Brotli'],
  ['Trusted SwiftUI helper','Typed props; real native input/action events','Native controls in a separate helper window','Own VStack layout; Primary explicitly unsupported','Native Email field and Button; keyboard entry verified',kb(results.native.bundleBytes)+' app + '+kb(results.native.launcherBytes)+' launcher; system frameworks excluded'],
];
const names={canvas:'Canvas authoring',dom:'Semantic DOM preview',web:'Real Web Awesome',native:'Trusted SwiftUI helper'};
const escape=(text:unknown)=>String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const cards=Object.entries(names).map(([key,name])=>`<article data-path="${key}"><h2>${name}</h2><p>${escape(comparison.timingDefinitions[key])}</p><div class="image"><img src="${key==='canvas'?'canvas-fixture.png':key==='dom'?'dom-fixture.png':key==='web'?'web-fixture.png':'native-fixture.png'}" alt="Actual ${name} rendering of the fixture"></div><p>${key==='native'?'Native capture uses two device pixels per point; displayed at its logical size.':'Chrome capture uses one device pixel per CSS pixel.'}</p></article>`).join('');
const timings=Object.entries(names).map(([key,name])=>`<tr><th>${name}</th><td>${results[key].updateMilliseconds.p50.toFixed(2)} ms</td><td>${results[key].updateMilliseconds.p95.toFixed(2)} ms</td><td>${escape(comparison.timingDefinitions[key])}</td></tr>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Real-library preview decision · Sugar Maple</title><style>
:root{font-family:system-ui;color:#17233d;background:#f3f6fb}*{box-sizing:border-box}body{margin:0}main{max-width:1450px;margin:auto;padding:40px 28px}h1{font-size:36px;line-height:1.1;max-width:850px}h2{font-size:20px}p{line-height:1.6;max-width:1050px}.eyebrow{color:#2563eb;font-size:12px;font-weight:700;letter-spacing:1px}.decision{padding:20px 24px;background:#fff4df;border:1px solid #ebc981;border-radius:12px;margin:24px 0}.decision strong{color:#75470a}.controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:24px 0}select,button{font:inherit;padding:8px 12px;border:1px solid #b9c6dc;border-radius:6px;background:white;color:#17233d}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}article{background:white;border:1px solid #dbe3ef;border-radius:10px;padding:18px;min-width:0}article p{font-size:12px;min-height:58px;color:#55627a}.image{height:390px;overflow:auto;background:#fff;border:1px solid #e2e7ef;display:flex;align-items:flex-start;justify-content:center}.image img{width:100%;max-width:400px;height:auto}article[hidden]{display:none}.scroll{overflow:auto;background:white;border:1px solid #dbe3ef;border-radius:10px;margin:16px 0 28px}table{border-collapse:collapse;width:100%;min-width:800px;font-size:13px}th,td{padding:14px;text-align:left;vertical-align:top;border-bottom:1px solid #e2e7ef;line-height:1.5}thead{background:#eaf0f9}th{min-width:160px}code{font-size:12px}a{color:#1d4ed8}.note{font-size:13px;color:#55627a}details{padding:16px;background:white;border:1px solid #dbe3ef;border-radius:8px}pre{font-size:11px;overflow:auto;max-height:300px}footer{font-size:12px;color:#55627a;margin-top:24px}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.grid{grid-template-columns:1fr}main{padding:24px 16px}h1{font-size:28px}}
</style></head><body><main><p class="eyebrow">SUGAR MAPLE · EXECUTABLE LIBRARY DISCOVERY · OCTOBER 2, 2026</p><h1>Real libraries work. Props alone do not preserve the authored UI.</h1><p>The same pinned Button/Input/Card fixture was exercised through the actual Canvas editor, semantic DOM preview, Web Awesome 3.14.0 and a separately sandboxed SwiftUI helper. These are real rendered consumers, with explicit limits on what each path proves.</p>
<div class="decision"><strong>Decision: GO for continued opt-in fixed-source experiments. NO-GO for production integration or replacing the Canvas authoring model.</strong><p>Canvas and DOM geometry match exactly for this fixture. Real runtimes receive typed props, but currently omit the complete authored geometry/style/slot contract. <a href="https://github.com/zubair-io/Sugar-Maple/issues/88">Issue #88</a> tracks that fidelity work. Arbitrary code import, full VoiceOver and product-scale performance remain unproven.</p></div>
<div class="controls"><label>Show rendering <select id="path"><option value="all">All four paths</option>${Object.entries(names).map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select></label><button id="width">Use full columns</button></div><section class="grid" id="renderings">${cards}</section>
<h2>Capabilities and costs</h2><div class="scroll"><table><thead><tr>${['Path','Editability','Interaction','Fidelity','Accessibility evidence','Asset cost'].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((cell,i)=>`<${i?'td':'th'}>${escape(cell)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>
<p class="note">The production editor ships ${kb(cost.editor.raw)} raw assets (${kb(cost.editor.brotli)} per-file Brotli), including its fonts/chrome. The experiment host adds ${kb(cost.experimentHost.raw)} raw assets (${kb(cost.experimentHost.brotli)} Brotli). All shipped assets are counted; these totals are not initial-load network bytes, installed memory or a comparison against OS framework size.</p>
<h2>Measured geometry and supported variants</h2><p>The authored Card is at (20,20), 360 × 460; Input 260 × 56; Button 180 × 44. Canvas and semantic DOM have a maximum geometry delta of ${results.dom.largestCanvasGeometryDelta} CSS units. The real-package Card is 360 × ${results.web.geometry['wa-card'].height.toFixed(2)}, Input ${results.web.geometry['wa-input'].width.toFixed(2)} × ${results.web.geometry['wa-input'].height.toFixed(2)} and Button ${results.web.geometry['wa-button'].width.toFixed(2)} × ${results.web.geometry['wa-button'].height.toFixed(2)}.</p><p>Primary changes the Canvas source identity without changing its recorded semantic paint styles. Web Awesome renders <code>variant=brand</code>; the native mapping returns an explicit unsupported error. This is a supported-contract difference, not evidence of visual equivalence.</p>
<h2>Pipeline completion observations</h2><p>Thirty sequential warm updates per path. These boundaries differ: they cannot rank input latency, physical presentation or FPS. The native snapshot includes an intentional 50 ms scheduling wait. The small fixture does not establish product-scale performance.</p><div class="scroll"><table><thead><tr><th>Path</th><th>p50</th><th>p95</th><th>Completion boundary</th></tr></thead><tbody>${timings}</tbody></table></div>
<h2>What the product needs next</h2><p>Keep the authoritative scene, history and layout in Sugar Maple. Add an explicit supported projection contract for geometry, slots, tokens and local overrides; distinguish fallback appearance from real package appearance. Continue to reject unsupported native variants. Before arbitrary source execution, prove stronger isolation and the production native bridge boundary, including navigation and resource behavior.</p><p>The native helper is a separate real UI process; its PNG path demonstrates bounded handoff, not an interactive native surface embedded in the Canvas. Full VoiceOver, physical presentation/input latency and whole-app memory remain part of the wider release and accessibility work.</p>
<details><summary>Scope and recorded evidence</summary><pre>${escape(JSON.stringify({recordedAt:comparison.recordedAt,scope:comparison.scope,timingDefinitions:comparison.timingDefinitions,limitations:comparison.limitations,webARIA:results.web.accessibility,DOMARIA:results.dom.accessibility,CanvasARIA:results.canvas.accessibility},null,2))}</pre></details>
<footer>Candidate discovery evidence for <a href="https://github.com/zubair-io/Sugar-Maple/issues/51">#51</a>. Web runtime #86 and native helper #87 require verified main delivery. Broader product/native fidelity, accessibility and post-MVP interoperability remain tracked separately.</footer></main><script>const picker=document.querySelector('#path');picker.addEventListener('change',()=>{document.querySelectorAll('[data-path]').forEach(card=>{card.hidden=picker.value!=='all'&&card.dataset.path!==picker.value;});});document.querySelector('#width').addEventListener('click',()=>{const grid=document.querySelector('#renderings');grid.style.gridTemplateColumns=grid.style.gridTemplateColumns?'':'repeat(2,minmax(0,1fr))';});</script></body></html>`;
await Bun.write(resolve(folder,'index.html'),html);
console.log('Wrote source-bound real-library comparison report');
