import { validateManifest } from './library-schema';

// Metadata only. Importing it in the editor never loads or evaluates this package.
export const webAwesomeManifest = validateManifest({
  manifestVersion: 1,
  revision: '1.0.0',
  id: 'web-awesome',
  name: 'Web Awesome',
  package: { name: '@awesome.me/webawesome', version: '3.14.0' },
  dependencies: {
    '@ctrl/tinycolor': '4.1.0',
    '@floating-ui/dom': '1.8.0',
    '@konnorr/qr-creator': '1.1.0',
    '@lit-labs/ssr': '4.1.0',
    '@lit-labs/ssr-client': '1.1.8',
    '@lit/context': '1.1.6',
    '@lit/react': '1.0.8',
    '@shoelace-style/animations': '1.2.0',
    '@shoelace-style/localize': '3.2.3',
    'composed-offset-position': '0.0.6',
    lit: '3.3.3',
    marked: '11.2.0',
    nanoid: '5.1.16',
  },
  webStyles: ['@awesome.me/webawesome/dist/styles/webawesome.css'],
  swiftSDK: { name: 'SwiftUI', version: 'macOS 14 minimum - system SwiftUI' },
  tokenMappings: { '--wa-color-brand-fill-loud': 'brand.primary' },
  components: {
    Button: {
      name: 'Web Awesome Button',
      semanticKind: 'button',
      width: 180,
      height: 44,
      props: {
        label: {
          type: 'string',
          default: 'Button',
          maxLength: 20000,
          semantic: 'text',
          webAttribute: null,
        },
        disabled: {
          type: 'boolean',
          default: false,
          semantic: 'disabled',
          webAttribute: 'disabled',
        },
        variant: {
          type: 'enum',
          default: 'neutral',
          values: ['neutral', 'brand', 'success', 'warning', 'danger'],
          semantic: null,
          webAttribute: 'variant',
        },
        appearance: {
          type: 'enum',
          default: 'accent',
          values: ['accent', 'filled-outlined', 'filled', 'outlined', 'plain'],
          semantic: null,
          webAttribute: 'appearance',
        },
      },
      slots: [''],
      variants: {
        Default: {},
        Primary: { variant: 'brand' },
        Disabled: { disabled: true },
      },
      defaultVariant: 'Default',
      web: {
        tag: 'wa-button',
        symbol: 'WaButton',
        module: '@awesome.me/webawesome/dist/components/button/button.js',
      },
      swift: {
        module: 'SwiftUI',
        symbol: 'Button',
        adapter: 'button',
        platforms: ['macOS'],
        supportedVariants: ['Default', 'Disabled'],
      },
    },
    Input: {
      name: 'Web Awesome Input',
      semanticKind: 'input',
      width: 260,
      height: 56,
      props: {
        label: {
          type: 'string',
          default: 'Email',
          maxLength: 200,
          semantic: 'accessibleLabel',
          webAttribute: 'label',
        },
        placeholder: {
          type: 'string',
          default: 'Your email',
          maxLength: 20000,
          semantic: 'text',
          webAttribute: 'placeholder',
        },
        value: {
          type: 'string',
          default: '',
          maxLength: 20000,
          semantic: 'initialValue',
          webAttribute: 'value',
        },
        type: {
          type: 'enum',
          default: 'email',
          values: ['text', 'email', 'password'],
          semantic: 'inputType',
          webAttribute: 'type',
        },
        disabled: {
          type: 'boolean',
          default: false,
          semantic: 'disabled',
          webAttribute: 'disabled',
        },
      },
      slots: [],
      variants: { Default: {}, Disabled: { disabled: true } },
      defaultVariant: 'Default',
      web: {
        tag: 'wa-input',
        symbol: 'WaInput',
        module: '@awesome.me/webawesome/dist/components/input/input.js',
      },
      swift: {
        module: 'SwiftUI',
        symbol: 'TextField',
        adapter: 'input',
        platforms: ['macOS'],
        supportedVariants: ['Default', 'Disabled'],
      },
    },
    Card: {
      name: 'Web Awesome Card',
      semanticKind: 'frame',
      width: 320,
      height: 240,
      props: {
        padding: {
          type: 'number',
          default: 16,
          min: 0,
          max: 100,
          semantic: 'padding',
          webAttribute: null,
        },
      },
      slots: ['', 'header', 'footer', 'media', 'actions'],
      variants: { Default: {} },
      defaultVariant: 'Default',
      web: {
        tag: 'wa-card',
        symbol: 'WaCard',
        module: '@awesome.me/webawesome/dist/components/card/card.js',
        styleBindings: { '--spacing': 'padding' },
      },
      swift: {
        module: 'SwiftUI',
        symbol: 'VStack',
        adapter: 'card',
        platforms: ['macOS'],
        supportedVariants: ['Default'],
      },
    },
  },
});
