import { runOwnedBrowserSuite } from "./owned-browser-server";

await runOwnedBrowserSuite(
  [
    "chrome-e2e",
    "layers-window-e2e",
    "editor-e2e",
    "canvas-e2e",
    "canvas-transform-e2e",
    "lock-editing-e2e",
    "drawing-e2e",
    "canvas-placement-e2e",
    "inspector-layout-e2e",
    "chrome-theme-e2e",
    "selection-inspector-e2e",
    "reparent-e2e",
    "canvas-parity-e2e",
    "typography-e2e",
    "text-editing-e2e",
    "canvas-performance",
    "file-menu-e2e",
    "autosave-e2e",
    "forward-metadata-e2e",
    "file-tabs-e2e",
    "selection-e2e",
    "responsive-e2e",
    "scene-border-e2e",
    "prototype-forms-e2e",
    "preview-inspect-e2e",
    "handoff-e2e",
    "web-consumer",
    "web-copy-e2e",
    "maple-design-e2e",
    "components-e2e",
    "repeat-data-e2e",
    "repeat-drops-e2e",
    "repeat-handles-e2e",
    "library-e2e",
    "library-consumer",
    "folders-e2e",
    "comments-e2e",
  ].map((name) => `src/web/tests/${name}.ts`),
);
